### ISSUE TITLE
agoraDemo在Android7.0上crash

### ISSUE THREAD

**Issue by Kendy6225** [ksvc/KSYDiversityLive_Android#22]
android 7.0上运行AgoraDemo崩溃
![crash](https://cloud.githubusercontent.com/assets/24692629/23005093/43e3f148-f435-11e6-8c21-07338b61191e.png)

**Comment by sujia** [comment]
@Kendy6225 我这边不能复现你的问题。
从crash堆栈来看，提示找不到onVideoFrame方法，你是不是修改了demo程序?
如果没修改代码的话，这个方法的signature应该跟https://github.com/ksvc/KSYDiversityLive_Android/blob/master/Agora/demo/src/main/jni/jni_RemoteDataObserver.cpp#L140 一样
