### ISSUE TITLE
UVC项目预览视频图像方法错位

### ISSUE THREAD

**Issue by jiaminfu** [ksvc/KSYDiversityLive_Android#67]
预览视频中图像方向错位　本来是右边的显示为左边　　但是拉流显示的图像又是正常的　　因为上传图片失败所以没上传　　已经上传到QQ群中

**Comment by buliaoyin** [comment]
UVC摄像头默认被作为前置摄像头，预览画面会做镜像，推流出去的时候又会镜像一次。  
如果要把预览画面镜像回去，可以调用mStreamer.getImgTexPreviewMixer().setMirror(0, true);
