### ISSUE TITLE
对方连麦设置的分辨率和主播不一样时 画面变形

### ISSUE THREAD

**Issue by a544393709** [ksvc/KSYDiversityLive_Android#72]
![default](https://user-images.githubusercontent.com/22026792/33005024-84a38c9c-cd89-11e7-8f00-7099e808d87d.jpg)

**Comment by zanxiaofei** [comment]
是对端的数据显示异常？还是主播的显示异常？
双方都是Android嘛？使用Demo确认过嘛？
另外麻烦说明一下使用的SDK的版本号，双方的分辨率设置情况、机型

**Comment by a544393709** [comment]
demo 试过也是一个效果 试了几个手机都一样，用的是金山云声网连麦的demo ，对方使用的是 声网的demo  
 用金山云声网连麦demo分辨率是默认的， 
  private int mVideoProfile = VideoProfile.VIDEO_PROFILE_360P_3;  //360*640
声网demo 不是这个比例的 都会出现图片的情况

**Comment by a544393709** [comment]
主播界面，对方数据端数据

**Comment by a544393709** [comment]
两个金山云的demo  不同分辨率  是正常的

**Comment by zanxiaofei** [comment]
demo正常的话，参考一下demo的kit类，看是否有什么地方遗漏了

**Comment by a544393709** [comment]
是两个金山云的demo  是正常的， 我们现在 iOS 端使用的是声网的demo  相互连   金山云的demo 会出现画面异常问题

**Comment by a544393709** [comment]
![Uploading 金山云声网连麦demo.jpg…]()
这是金山云声网连麦的demo效果
